// <auto-generated />
using MCPDemo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MCPDemo.Data.Migrations
{
    [DbContext(typeof(CovidDataDbContext))]
    [Migration("20250524193927_LocationsTable_RemoveIsoCountryCode")]
    partial class LocationsTable_RemoveIsoCountryCode
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MCPDemo.Data.Entities.Location", b =>
                {
                    b.Property<string>("LocationKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlaceId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubRegion1Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubRegion2Code")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LocationKey");

                    b.ToTable("Locations");
                });
#pragma warning restore 612, 618
        }
    }
}
